name: Go

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.25"
          cache: true

      - name: Install goimports
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          export PATH="$HOME/go/bin:$PATH"

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Lint
        run: pre-commit run -a

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.24", "1.25"]
    name: Test ${{ matrix.go-version == '1.25' && '(latest)' || '(old)' }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Set up gotestfmt
        uses: GoTestTools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -json -v ./... 2>&1 | gotestfmt
